"""Add contact_type field to ClientContact

Revision ID: d9d7481d1870
Revises: add_subbrand_001
Create Date: 2025-08-14 09:55:51.789917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9d7481d1870'
down_revision = 'add_subbrand_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('client_contacts', schema=None) as batch_op:
        batch_op.drop_column('contact_type')

    # ### end Alembic commands ###
